### ISSUE TITLE
Make transition rates time-varying

### ISSUE THREAD

**Issue by lcreteig** [UPOD-datascience/Sirum#2]
# Background

The simple SIR model has two parameters that determine the transition rates between the `S` `I` and `R` compartments.

- `beta` (`S` to `I`): contact/transmission rate = number of contacts per person per unit of time, multiplied by probability of transmitting the disease.
- `gamma` (`I` to `R`): removal rate = number of people that recovered or died, divided by total number of infected, per unit of time.

Because of measures like social distancing, testing and quarantining, increased attention to hygiene etc., **`beta` will likely change during the epidemic**. I don't immediately see a reason why `gamma` would change (perhaps with medical treatment).

## Typical ways to model change

1. **Seasonality**: multiply `beta` by some oscillatory function of time
2. **Interventions**: run a different model with modified `beta` for some time steps, then compare with baseline model (without intervention)

# Suggested approach:

In equation 11 in [1], `beta(t)` a function of `I(t)` and `R(t)`, under the assumption that `S` is equal to the size of the population (_N_).

## Questions

- Is the assumption on S still justified, now that the outbreak is transitioning to later stages?
- Can our hyperparameter optimization actually estimate time-varying parameters?

## TODO
- [ ] Implement equation 11 from [1] in discrete-time equations in `Fitting_to_Compartmental_Models.ipynb`
- [ ] Have someone more math-savvy review implementation, and equations in [1]

_See also [2] for another equation for changing contact rate_

# References
[1] A Time-dependent SIR model for COVID-19 with Undetectable Infected Persons: [arXiv](https://arxiv.org/abs/2003.00122)
[2] Dynamics of COVID-19 pandemic at constant and time-dependent contact rates [medRxiv](https://doi.org/10.1101/2020.03.13.20035485)

**Comment by bramiozo** [comment]
Gamma will definitely change for the worse if we reach the limit of the IC-capacity but it is indeed hard to see gamma-variability in the SIR setup. On the individual level it of course depends on the medical background, the demographics etc. but we don't have that distinction in the SIR model. 

An alternative option for all parameters, now assumed constant, is to make regression models using retrospective data :). 

A simple option for Beta is to just use a changelist, as is done in the SEIRSplus repos. 
I.e. [beta1, beta1, beta1......, beta1 + Delta... etc]
